# Generated by Django 5.1.4 on 2025-02-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'employee'), ('manager', 'manager'), ('hr_manager', 'hr_manager'), ('administrator', 'administrator')], default='employee', max_length=20, null=True),
        ),
    ]
