# Generated by Django 5.1.4 on 2025-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_trainingprogrammodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='points',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
